name: policy_dukaan
description: "Policy Dukaan Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  http: ^1.6.0
  shared_preferences: ^2.5.4
  razorpay_flutter: ^1.4.0
  file_picker: ^10.3.8
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  excel: ^4.0.6
  fl_chart: ^1.1.1
  fluttertoast: ^8.2.8
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
